version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
  db:
    image: postgres:11
    env_file: .env
    expose:
      - 5432
