# GLOBAL

namespace: sql

# Flask

flaskReplicas: 1

flaskImage: strizha/flask-web

flaskIP:
  LBIP: 127.0.0.1

flaskPort: 
  clusterPort: 80
  outPort: 8080

# Postgres

postgresReplicas: 1

postgresImage: postgres:11

postgresPort:
  clusterPort: 5432