apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: flask-{{ .Release.Name }}
spec:
  replicas: {{ .Values.flaskReplicas }}
  selector:
    matchLabels:
      app: flask-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: flask-{{ .Release.Name }}
    spec:
      containers:
      - name: flask-{{ .Release.Name }}
        image: {{ .Values.flaskImage }}
        ports:
        - containerPort: {{ .Values.flaskPort.clusterPort }}