apiVersion: v1
kind: Service
metadata:
  name: flask-service-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: flask-{{ .Release.Name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.flaskPort.outPort }}
    targetPort: {{ .Values.flaskPort.clusterPort }}
  selector:
    app: flask-{{ .Release.Name }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.flaskIP.LBIP }}