apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-{{ .Release.Name }}
spec:
  replicas: {{ .Values.postgresReplicas }}
  selector:
    matchLabels:
      app: postgres-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: postgres-{{ .Release.Name }}
    spec:
      containers:
      - name: postgres-{{ .Release.Name }}
        image: {{ .Values.postgresImage }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config-{{ .Release.Name }}
        - name: "POSTGRES_USER"
          valueFrom:
            secretKeyRef:
              key: username
              name: mysecret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysecret
        ports:
          - containerPort: {{ .Values.postgresPort.clusterPort }}
            name: postgres-{{ .Release.Name }}
