apiVersion: v1
kind: Service
metadata:
  name: postgres-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.postgresPort.clusterPort }}
  selector:
    app: postgres-{{ .Release.Name }}
