apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: postgres-config-{{ .Release.Name }}
  labels:
    app: postgres-{{ .Release.Name }}
data:
  POSTGRES_DB: demo_db
#  POSTGRES_USER: strizh
#  POSTGRES_PASSWORD: Za1eNogLa$oeTax1
